"""Add category to template

Revision ID: 8aca6be030d9
Revises: d52383c5d78b
Create Date: 2026-06-02 06:30:42.282888

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aca6be030d9'
down_revision = 'd52383c5d78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'category')
    # ### end Alembic commands ###
